// Clear error state
function clearError(inputId, errorId) {
    const input = document.getElementById(inputId);
    const error = document.getElementById(errorId);
    
    if (input) {
        input.classList.remove('error');
    }
    if (error) {
        error.classList.remove('show');
        error.textContent = '';
    }
}

// Show error state
function showError(inputId, errorId, message) {
    const input = document.getElementById(inputId);
    const error = document.getElementById(errorId);
    
    if (input) {
        input.classList.add('error');
    }
    if (error) {
        error.classList.add('show');
        error.textContent = message;
    }
}

// Clear all errors
function clearAllErrors() {
    clearError('namaToko', 'errorNamaToko');
    clearError('urlToko', 'errorUrlToko');
    clearError('nomorTelepon', 'errorTelepon');
    clearError('email', 'errorEmail');
    clearError('password', 'errorPassword');
}

// Validate email format
function isValidEmail(email) {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
}

// Validate phone number (10-13 digits)
function isValidPhone(phone) {
    const phoneRegex = /^[0-9]{10,13}$/;
    return phoneRegex.test(phone.replace(/[\s-]/g, ''));
}

// Format phone number input (only numbers)
function formatPhoneInput(input) {
    let value = input.value.replace(/\D/g, '');
    
    // Limit to 13 digits
    if (value.length > 13) {
        value = value.substring(0, 13);
    }
    
    input.value = value;
}

// Validate URL format (only lowercase letters, numbers, and hyphens)
function isValidUrl(url) {
    const urlRegex = /^[a-z0-9-]+$/;
    return urlRegex.test(url) && url.length >= 3 && url.length <= 30;
}

// Format URL input (convert to lowercase, remove invalid characters)
function formatUrlInput(input) {
    let value = input.value.toLowerCase();
    
    // Remove invalid characters (keep only letters, numbers, and hyphens)
    value = value.replace(/[^a-z0-9-]/g, '');
    
    // Remove consecutive hyphens
    value = value.replace(/-+/g, '-');
    
    // Remove leading/trailing hyphens
    value = value.replace(/^-+|-+$/g, '');
    
    // Limit length
    if (value.length > 30) {
        value = value.substring(0, 30);
    }
    
    input.value = value;
    
    // Update preview
    updateUrlPreview(value);
}

// Update URL preview
function updateUrlPreview(customUrl) {
    const previewUrl = document.querySelector('.preview-url');
    const urlPreview = document.getElementById('urlPreview');
    const urlHint = document.getElementById('urlHint');
    
    if (previewUrl) {
        previewUrl.textContent = `onmenu.id/${customUrl || ''}`;
    }
    
    // Show visual feedback for auto-generated URLs
    if (urlPreview && !urlManuallyEdited && customUrl) {
        urlPreview.classList.add('auto-generated');
        if (urlHint) {
            urlHint.classList.add('show');
        }
    } else if (urlPreview) {
        urlPreview.classList.remove('auto-generated');
        if (urlHint) {
            urlHint.classList.remove('show');
        }
    }
}

// Check if URL is already taken (simulate server check)
function isUrlTaken(url) {
    // In real app, this would be an API call
    const takenUrls = ['admin', 'api', 'www', 'mail', 'support', 'help', 'about', 'contact'];
    return takenUrls.includes(url.toLowerCase());
}

// Generate URL suggestion from store name
function generateUrlSuggestion(storeName) {
    let suggestion = storeName.toLowerCase()
        .replace(/[^a-z0-9\s]/g, '') // Remove special characters
        .replace(/\s+/g, '-') // Replace spaces with hyphens
        .replace(/-+/g, '-') // Remove consecutive hyphens
        .replace(/^-+|-+$/g, ''); // Remove leading/trailing hyphens
    
    // Limit length
    if (suggestion.length > 30) {
        suggestion = suggestion.substring(0, 30);
    }
    
    return suggestion;
}

// Track if URL has been manually edited
let urlManuallyEdited = false;
let lastAutoGeneratedUrl = '';

// Smart auto-fill URL from store name
function autoFillUrl(storeName) {
    const urlToko = document.getElementById('urlToko');
    if (!urlToko) return;
    
    const currentUrl = urlToko.value.trim();
    const newSuggestion = generateUrlSuggestion(storeName);
    
    // Only auto-fill if:
    // 1. URL field is empty, OR
    // 2. Current URL matches the last auto-generated URL (not manually edited)
    if (!urlManuallyEdited && (currentUrl === '' || currentUrl === lastAutoGeneratedUrl)) {
        urlToko.value = newSuggestion;
        lastAutoGeneratedUrl = newSuggestion;
        updateUrlPreview(newSuggestion);
        
        // Clear any existing errors
        clearError('urlToko', 'errorUrlToko');
        const container = document.querySelector('.url-input-container');
        if (container) container.classList.remove('error');
    }
}

// Reset URL manual edit tracking
function resetUrlTracking() {
    urlManuallyEdited = false;
    lastAutoGeneratedUrl = '';
}

// Validate form
function validateForm() {
    clearAllErrors();
    
    const namaToko = document.getElementById('namaToko');
    const urlToko = document.getElementById('urlToko');
    const nomorTelepon = document.getElementById('nomorTelepon');
    const email = document.getElementById('email');
    const password = document.getElementById('password');
    
    let hasError = false;
    
    // Validate Nama Toko (required)
    if (!namaToko.value.trim()) {
        showError('namaToko', 'errorNamaToko', 'Nama toko wajib diisi');
        hasError = true;
    }
    
    // Validate URL Toko (required + format + availability)
    if (!urlToko.value.trim()) {
        showError('urlToko', 'errorUrlToko', 'URL toko wajib diisi');
        // Add error class to container
        const container = document.querySelector('.url-input-container');
        if (container) container.classList.add('error');
        hasError = true;
    } else if (!isValidUrl(urlToko.value.trim())) {
        showError('urlToko', 'errorUrlToko', 'URL hanya boleh huruf kecil, angka, dan tanda hubung (3-30 karakter)');
        const container = document.querySelector('.url-input-container');
        if (container) container.classList.add('error');
        hasError = true;
    } else if (isUrlTaken(urlToko.value.trim())) {
        showError('urlToko', 'errorUrlToko', 'URL sudah digunakan, silakan pilih yang lain');
        const container = document.querySelector('.url-input-container');
        if (container) container.classList.add('error');
        hasError = true;
    }
    
    // Validate Nomor Telepon (required + format)
    if (!nomorTelepon.value.trim()) {
        showError('nomorTelepon', 'errorTelepon', 'Nomor telepon wajib diisi');
        hasError = true;
    } else if (!isValidPhone(nomorTelepon.value.trim())) {
        showError('nomorTelepon', 'errorTelepon', 'Nomor telepon harus 10-13 digit');
        hasError = true;
    }
    
    // Validate Email (required + format)
    if (!email.value.trim()) {
        showError('email', 'errorEmail', 'Email wajib diisi');
        hasError = true;
    } else if (!isValidEmail(email.value.trim())) {
        showError('email', 'errorEmail', 'Format email tidak valid');
        hasError = true;
    }
    
    // Validate Password (required + min length)
    if (!password.value) {
        showError('password', 'errorPassword', 'Kata sandi wajib diisi');
        hasError = true;
    } else if (password.value.length < 6) {
        showError('password', 'errorPassword', 'Kata sandi minimal 6 karakter');
        hasError = true;
    }
    
    return !hasError;
}

// Handle form submit
function handleSubmit(e) {
    e.preventDefault();
    
    if (validateForm()) {
        const namaToko = document.getElementById('namaToko').value.trim();
        const urlToko = document.getElementById('urlToko').value.trim();
        const nomorTelepon = document.getElementById('nomorTelepon').value.trim();
        const email = document.getElementById('email').value.trim();
        const password = document.getElementById('password').value;
        
        // Save to localStorage (in real app, send to server)
        const userData = {
            namaToko,
            urlToko,
            nomorTelepon,
            email,
            password,
            registeredAt: new Date().toISOString()
        };
        
        localStorage.setItem('userData', JSON.stringify(userData));
        localStorage.setItem('isLoggedIn', 'true');
        
        showToast('Pendaftaran berhasil!', 'success');
        
        setTimeout(() => {
            window.location.href = 'dasboard.html';
        }, 1000);
    }
}

// Initialize
function init() {
    const form = document.getElementById('formDaftar');
    if (form) {
        form.addEventListener('submit', handleSubmit);
    }
    
    // Phone number formatting
    const phoneInput = document.getElementById('nomorTelepon');
    if (phoneInput) {
        phoneInput.addEventListener('input', (e) => {
            formatPhoneInput(e.target);
        });
        
        // Clear error on input
        phoneInput.addEventListener('input', () => {
            clearError('nomorTelepon', 'errorTelepon');
        });
    }
    
    // Clear error on input for other fields
    const namaToko = document.getElementById('namaToko');
    if (namaToko) {
        namaToko.addEventListener('input', () => {
            clearError('namaToko', 'errorNamaToko');
            
            // Smart auto-fill URL from store name
            autoFillUrl(namaToko.value);
        });
    }
    
    // URL input formatting and validation
    const urlToko = document.getElementById('urlToko');
    if (urlToko) {
        // Track when user starts typing (manual edit)
        urlToko.addEventListener('input', (e) => {
            const currentValue = e.target.value;
            const formattedValue = currentValue.toLowerCase().replace(/[^a-z0-9-]/g, '').replace(/-+/g, '-').replace(/^-+|-+$/g, '');
            
            // Check if this is a manual edit (not auto-generated)
            if (currentValue !== lastAutoGeneratedUrl && currentValue !== '') {
                urlManuallyEdited = true;
            }
            
            // If user clears the field completely, reset tracking
            if (currentValue === '') {
                resetUrlTracking();
                // Auto-fill from current store name if available
                const storeNameValue = namaToko ? namaToko.value.trim() : '';
                if (storeNameValue) {
                    autoFillUrl(storeNameValue);
                    return; // Skip the rest since autoFillUrl handles formatting
                }
            }
            
            formatUrlInput(e.target);
            
            // Clear error and container error class
            clearError('urlToko', 'errorUrlToko');
            const container = document.querySelector('.url-input-container');
            if (container) container.classList.remove('error');
        });
        
        // Track focus to detect manual editing intent
        urlToko.addEventListener('focus', () => {
            // If user focuses on URL field and it has content, consider it manual editing
            if (urlToko.value.trim() !== '') {
                urlManuallyEdited = true;
            }
        });
        
        // Real-time validation on blur
        urlToko.addEventListener('blur', () => {
            const value = urlToko.value.trim();
            if (value && isUrlTaken(value)) {
                showError('urlToko', 'errorUrlToko', 'URL sudah digunakan, silakan pilih yang lain');
                const container = document.querySelector('.url-input-container');
                if (container) container.classList.add('error');
            }
        });
    }
    
    const emailInput = document.getElementById('email');
    if (emailInput) {
        emailInput.addEventListener('input', () => {
            clearError('email', 'errorEmail');
        });
    }
    
    const passwordInput = document.getElementById('password');
    if (passwordInput) {
        passwordInput.addEventListener('input', () => {
            clearError('password', 'errorPassword');
        });
    }
}

// Run when DOM is ready
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
} else {
    init();
}
